"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "ru" | "uz"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    dashboard: "Dashboard",
    home: "Admin",
    users: "Administrator",
    categories: "Categories",
    tags: "Tags",
    managers: "Management",
    articles: "News",
    comments: "Comments",
    appeals: "Appeals",
    banners: "Banners",
    settings: "Settings",
    logout: "Logout",
    administrator: "Administrator",
    filters: "Filters",
    name: "Name",
    fullName: "Full Name",
    position: "Position",
    phoneNumber: "Phone Number",
    bio: "Biography",
    id: "ID",
    apply: "Apply",
    clear: "Clear",
    add: "Add",
    language: "Language",
    title: "Title",
    alias: "Alias",
    created: "Created",
    actions: "Actions",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    parent: "Parent",
    author: "Author",
    views: "Views",
    image: "Image",
    category: "Category",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    deleteConfirm: "Are you sure you want to delete this item?",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    save: "Save",
    addTag: "Add Tag",
    addCategory: "Add Category",
    addUser: "Add User",
    addManager: "Add Manager",
    editManager: "Edit Manager",
    addArticle: "Add News",
    editArticle: "Edit News",
    nameTranslit: "Name Transliteration",
    descriptionTranslit: "Description Transliteration",
    description: "Description",
    selectLanguage: "Select Language",
    selectParentCategory: "Select Parent Category",
    selectCategory: "Select Category",
    parentCategory: "Parent Category",
    poster: "Poster",
    uploadPoster: "Upload Poster",
    uploadPhoto: "Upload Photo",
    uploadAudio: "Upload Audio",
    content: "Content",
    audio: "Audio",
    saving: "Saving...",
    roles: "Roles",
    editUser: "Edit User",
    changePassword: "Change Password",
    newPassword: "New Password",
    rowsPerPage: "Rows per page",
    newsType: "News Type",
    selectNewsType: "Select News Type",
    departmentsAndSectors: "Departments and Sectors",
    subordinateOrganizations: "Subordinate Organizations",
    regionalCouncils: "Regional Councils",
    department: "Department",
    sector: "Sector",
    organization: "Organization",
    institution: "Institution",
    region: "Region",
    address: "Address",
    selectType: "Select Type",
    all: "All",
    general: "General",
    notifications: "Notifications",
    security: "Security",
    appearance: "Appearance",
    customizeInterface: "Customize your interface",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    notificationPreferences: "Notification Preferences",
    manageNotifications: "Manage how you receive notifications",
    emailNotifications: "Email Notifications",
    pushNotifications: "Push Notifications",
    weeklyDigest: "Weekly Digest",
    securitySettings: "Security Settings",
    manageSecuritySettings: "Manage your security preferences",
    securityAlerts: "Security Alerts",
    twoFactorAuth: "Two-Factor Authentication",
    sessionTimeout: "Session Timeout",
    minutes: "minutes",
    activeDevices: "Active Devices",
    manageDevices: "Manage your active sessions",
    revoke: "Revoke",
    saveChanges: "Save Changes",
    chooseLanguage: "Choose your preferred language",
    preferredLanguage: "Preferred Language",
    editRegionalCouncil: "Edit Regional Council",
    editSubordinateOrganization: "Edit Subordinate Organization",
    editDepartment: "Edit Department",
    addDepartment: "Add Department",
    addSubordinateOrganization: "Add Subordinate Organization",
    addRegionalCouncil: "Add Regional Council",
  },
  ru: {
    dashboard: "Панель управления",
    home: "Администратор",
    users: "Администратор",
    categories: "Категории",
    tags: "Теги",
    managers: "Раҳбарият",
    articles: "Новости",
    comments: "Комментарии",
    appeals: "Обращения",
    banners: "Баннеры",
    settings: "Настройки",
    logout: "Выход",
    administrator: "Администратор",
    filters: "Фильтры",
    name: "Наименование",
    fullName: "Полное имя",
    position: "Должность",
    phoneNumber: "Номер телефона",
    bio: "Биография",
    id: "ID",
    apply: "Применить",
    clear: "Очистить",
    add: "Добавить",
    language: "Язык",
    title: "Название",
    alias: "Алиас",
    created: "Создано",
    actions: "Actions",
    login: "Вход",
    register: "Регистрация",
    email: "Эл. почта",
    password: "Пароль",
    confirmPassword: "Подтвердите пароль",
    parent: "Родитель",
    author: "Автор",
    views: "Кол-во просмотров",
    image: "Изображение",
    category: "Категория",
    darkMode: "Темный режим",
    lightMode: "Светлый режим",
    deleteConfirm: "Вы уверены, что хотите удалить этот элемент?",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    save: "Сохранить",
    addTag: "Добавить тег",
    addCategory: "Добавить категорию",
    addUser: "Добавить пользователя",
    addManager: "Добавить руководителя",
    editManager: "Редактировать руководителя",
    addArticle: "Добавить новость",
    editArticle: "Редактировать новость",
    nameTranslit: "Транслитерация имени",
    descriptionTranslit: "Транслитерация описания",
    description: "Описание",
    selectLanguage: "Выберите язык",
    selectParentCategory: "Выберите родительскую категорию",
    selectCategory: "Выберите категорию",
    parentCategory: "Родительская категория",
    poster: "Постер",
    uploadPoster: "Загрузить постер",
    uploadPhoto: "Загрузить фото",
    uploadAudio: "Загрузить аудио",
    content: "Содержание",
    audio: "Аудио",
    saving: "Сохранение...",
    roles: "Роли",
    editUser: "Редактировать пользователя",
    changePassword: "Изменить пароль",
    newPassword: "Новый пароль",
    rowsPerPage: "Строк на странице",
    newsType: "Тип новости",
    selectNewsType: "Выберите тип новости",
    departmentsAndSectors: "Отделы и секторы",
    subordinateOrganizations: "Подведомственные организации",
    regionalCouncils: "Региональные советы",
    department: "Отдел",
    sector: "Сектор",
    organization: "Организация",
    institution: "Учреждение",
    region: "Регион",
    address: "Адрес",
    selectType: "Выберите тип",
    all: "Все",
    general: "Общие",
    notifications: "Уведомления",
    security: "Безопасность",
    appearance: "Внешний вид",
    customizeInterface: "Настройте интерфейс",
    theme: "Тема",
    light: "Светлая",
    dark: "Темная",
    system: "Системная",
    notificationPreferences: "Настройки уведомлений",
    manageNotifications: "Управление уведомлениями",
    emailNotifications: "Email уведомления",
    pushNotifications: "Push-уведомления",
    weeklyDigest: "Еженедельный дайджест",
    securitySettings: "Настройки безопасности",
    manageSecuritySettings: "Управление параметрами безопасности",
    securityAlerts: "Оповещения безопасности",
    twoFactorAuth: "Двухфакторная аутентификация",
    sessionTimeout: "Тайм-аут сессии",
    minutes: "минут",
    activeDevices: "Активные устройства",
    manageDevices: "Управление активными сессиями",
    revoke: "Отозвать",
    saveChanges: "Сохранить изменения",
    chooseLanguage: "Выберите предпочитаемый язык",
    preferredLanguage: "Предпочитаемый язык",
    editRegionalCouncil: "Редактировать Областной совет",
    editSubordinateOrganization: "Редактировать Подчиненную организацию",
    editDepartment: "Редактировать Отдел",
    addDepartment: "Добавить Отдел",
    addSubordinateOrganization: "Добавить Подчиненную организацию",
    addRegionalCouncil: "Добавить Областной совет",
  },
  uz: {
    dashboard: "Boshqaruv paneli",
    home: "Administrator",
    users: "Administrator",
    categories: "Kategoriyalar",
    tags: "Teglar",
    managers: "Раҳбарият",
    articles: "Yangiliklar",
    comments: "Izohlar",
    appeals: "Murojaatlar",
    banners: "Bannerlar",
    settings: "Sozlamalar",
    logout: "Chiqish",
    administrator: "Administrator",
    filters: "Filtrlar",
    name: "Nomi",
    fullName: "To'liq ismi",
    position: "Lavozimi",
    phoneNumber: "Telefon raqami",
    bio: "Biografiya",
    id: "ID",
    apply: "Qo'llash",
    clear: "Tozalash",
    add: "Qo'shish",
    language: "Til",
    title: "Sarlavha",
    alias: "Taxallus",
    created: "Yaratilgan",
    actions: "Amallar",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    email: "Elektron pochta",
    password: "Parol",
    confirmPassword: "Parolni tasdiqlang",
    parent: "Ota-ona",
    author: "Muallif",
    views: "Ko'rishlar soni",
    image: "Rasm",
    category: "Kategoriya",
    darkMode: "Qorong'u rejim",
    lightMode: "Yorug'lik rejimi",
    deleteConfirm: "Haqiqatan ham ushbu elementni o'chirishni xohlaysizmi?",
    cancel: "Bekor qilish",
    delete: "O'chirish",
    edit: "Tahrirlash",
    save: "Saqlash",
    addTag: "Teg qo'shish",
    addCategory: "Kategoriya qo'shish",
    addUser: "Foydalanuvchi qo'shish",
    addManager: "Rahbar qo'shish",
    editManager: "Rahbarni tahrirlash",
    addArticle: "Yangilik qo'shish",
    editArticle: "Yangilikni tahrirlash",
    nameTranslit: "Ism transliteratsiyasi",
    descriptionTranslit: "Tavsif transliteratsiyasi",
    description: "Tavsif",
    selectLanguage: "Tilni tanlang",
    selectParentCategory: "Ota-ona kategoriyasini tanlang",
    selectCategory: "Kategoriyani tanlang",
    parentCategory: "Ota-ona kategoriyasi",
    poster: "Plakat",
    uploadPoster: "Plakatni yuklash",
    uploadPhoto: "Rasmni yuklash",
    uploadAudio: "Audio yuklash",
    content: "Kontent",
    audio: "Audio",
    saving: "Saqlash...",
    roles: "Rollar",
    editUser: "Foydalanuvchini tahrirlash",
    changePassword: "Parolni o'zgartirish",
    newPassword: "Yangi parol",
    rowsPerPage: "Har bir sahifadagi qatorlar",
    newsType: "Yangilik turi",
    selectNewsType: "Yangilik turini tanlang",
    departmentsAndSectors: "Бўлим ва секторлар",
    subordinateOrganizations: "Тасарруфий ташкилотлар",
    regionalCouncils: "Ҳудудий Кенгашлар",
    department: "Бўлим",
    sector: "Сектор",
    organization: "Ташкилот",
    institution: "Муассаса",
    region: "Вилоят",
    address: "Манзил",
    selectType: "Турни танланг",
    all: "Барчаси",
    general: "Umumiy",
    notifications: "Bildirishnomalar",
    security: "Xavfsizlik",
    appearance: "Ko'rinish",
    customizeInterface: "Interfeysni sozlash",
    theme: "Mavzu",
    light: "Yorug'",
    dark: "Qorong'u",
    system: "Tizim",
    notificationPreferences: "Bildirishnoma sozlamalari",
    manageNotifications: "Bildirishnomalarni boshqarish",
    emailNotifications: "Email xabarnomalar",
    pushNotifications: "Push-xabarnomalar",
    weeklyDigest: "Haftalik dayjest",
    securitySettings: "Xavfsizlik sozlamalari",
    manageSecuritySettings: "Xavfsizlik parametrlarini boshqarish",
    securityAlerts: "Xavfsizlik ogohlantirishlari",
    twoFactorAuth: "Ikki bosqichli autentifikatsiya",
    sessionTimeout: "Sessiya vaqti",
    minutes: "daqiqa",
    activeDevices: "Faol qurilmalar",
    manageDevices: "Faol seanslarni boshqarish",
    revoke: "Bekor qilish",
    saveChanges: "O'zgarishlarni saqlash",
    chooseLanguage: "Afzal ko'rgan tilni tanlang",
    preferredLanguage: "Afzal ko'rilgan til",
    editRegionalCouncil: "Вилоят Кенгашини таҳрирлаш",
    editSubordinateOrganization: "Қарам ташкилотни таҳрирлаш",
    editDepartment: "Бўлимни таҳрирлаш",
    addDepartment: "Бўлим қўшиш",
    addSubordinateOrganization: "Қарам ташкилот қўшиш",
    addRegionalCouncil: "Вилоят Кенгашини қўшиш",
  },
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["en", "ru", "uz"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string) => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)

